### ISSUE TITLE
support for rules configuration

### ISSUE THREAD

**Issue by artola** [mmkal/eslint-plugin-wrapper#2]
It seems that rules configuration is not possible, using the first example in the README I can not downgrade it to warn.

```
  rules: {
    'my-project/no-literals': 2,
  },
```

```
  1:1   error  Definition for rule 'my-project/no-literals' was not found  my-project/no-literals
```

It seems that the correct way is:

```
  rules: {
    'wrapper/my-project/no-literals': 2,
  },
```

**Comment by mmkal** [comment]
Yep. This wasn’t documented as well as it should have been, so put in a slightly better hint in the readme. Basically the library wraps each rule and takes ownership of it. The effect of that is that the rule will be prefixed.
